(function(){var m,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},n=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},ca=ba(this),q=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&n(c,a,{configurable:!0,writable:!0,value:b})}};
q("Symbol",function(a){if(a)return a;var b=function(f,h){this.g=f;n(this,"description",{configurable:!0,writable:!0,value:h})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ca[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&n(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});
var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},r=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");},t=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};q("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});
q("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var h=d[f];if(b.call(c,h,f,d)){b=h;break a}}b=void 0}return b}});
q("WeakMap",function(a){function b(){}function c(k){var l=typeof k;return l==="object"&&k!==null||l==="function"}function d(k){if(!t(k,f)){var l=new b;n(k,f,{value:l})}}function e(k){var l=Object[k];l&&(Object[k]=function(p){if(p instanceof b)return p;Object.isExtensible(p)&&d(p);return l(p)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),p=new a([[k,2],[l,3]]);if(p.get(k)!=2||p.get(l)!=3)return!1;p.delete(k);p.set(l,4);return!p.has(k)&&p.get(l)==4}catch(J){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var h=0,g=function(k){this.g=(h+=Math.random()+1).toString();if(k){k=r(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};g.prototype.set=function(k,l){if(!c(k))throw Error("Invalid WeakMap key");d(k);if(!t(k,f))throw Error("WeakMap key fail: "+k);k[f][this.g]=l;return this};g.prototype.get=function(k){return c(k)&&t(k,f)?k[f][this.g]:void 0};g.prototype.has=function(k){return c(k)&&t(k,f)&&t(k[f],this.g)};
g.prototype.delete=function(k){return c(k)&&t(k,f)&&t(k[f],this.g)?delete k[f][this.g]:!1};return g});
q("Map",function(a){if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var g=Object.seal({x:4}),k=new a(r([[g,"s"]]));if(k.get(g)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=k.entries(),p=l.next();if(p.done||p.value[0]!=g||p.value[1]!="s")return!1;p=l.next();return p.done||p.value[0].x!=4||p.value[1]!="t"||!l.next().done?!1:!0}catch(J){return!1}}())return a;var b=new WeakMap,c=function(g){this[0]={};this[1]=
f();this.size=0;if(g){g=r(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}};c.prototype.set=function(g,k){g=g===0?0:g;var l=d(this,g);l.list||(l.list=this[0][l.id]=[]);l.B?l.B.value=k:(l.B={next:this[1],I:this[1].I,head:this[1],key:g,value:k},l.list.push(l.B),this[1].I.next=l.B,this[1].I=l.B,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.B&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.B.I.next=g.B.next,g.B.next.I=g.B.I,g.B.head=
null,this.size--,!0):!1};c.prototype.clear=function(){this[0]={};this[1]=this[1].I=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).B};c.prototype.get=function(g){return(g=d(this,g).B)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,function(g){return g.value})};c.prototype.forEach=function(g,k){for(var l=this.entries(),p;!(p=l.next()).done;)p=
p.value,g.call(k,p[1],p[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,k){var l=k&&typeof k;l=="object"||l=="function"?b.has(k)?l=b.get(k):(l=""+ ++h,b.set(k,l)):l="p_"+k;var p=g[0][l];if(p&&t(g[0],l))for(g=0;g<p.length;g++){var J=p[g];if(k!==k&&J.key!==J.key||k===J.key)return{id:l,list:p,index:g,B:J}}return{id:l,list:p,index:-1,B:void 0}},e=function(g,k){var l=g[1];return da(function(){if(l){for(;l.head!=g[1];)l=l.I;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};
l=null}return{done:!0,value:void 0}})},f=function(){var g={};return g.I=g.next=g.head=g},h=0;return c});q("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)t(b,d)&&c.push(b[d]);return c}});var ea=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};
q("Array.prototype.keys",function(a){return a?a:function(){return ea(this,function(b){return b})}});q("Array.prototype.values",function(a){return a?a:function(){return ea(this,function(b,c){return c})}});
q("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(g){return g};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var fa=fa||{},u=this||self,ha=function(a){var b=typeof a;b=b!="object"?b:a?Array.isArray(a)?"array":b:"null";return b=="array"||b=="object"&&typeof a.length=="number"},v=function(a){var b=typeof a;return b=="object"&&a!=null||b=="function"},ia=function(a,b,c){return a.call.apply(a.bind,arguments)},ja=function(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,
d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},w=function(a,b,c){w=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ia:ja;return w.apply(null,arguments)},x=function(a,b){function c(){}c.prototype=b.prototype;a.T=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.eb=function(d,e,f){for(var h=Array(arguments.length-2),g=2;g<arguments.length;g++)h[g-2]=arguments[g];return b.prototype[e].apply(d,h)}},ka=function(a){return a};var la,y;a:{for(var ma=["CLOSURE_FLAGS"],z=u,na=0;na<ma.length;na++)if(z=z[ma[na]],z==null){y=null;break a}y=z}var oa=y&&y[610401301];la=oa!=null?oa:!1;function pa(){var a=u.navigator;return a&&(a=a.userAgent)?a:""}var A,qa=u.navigator;A=qa?qa.userAgentData||null:null;function ra(a){return la?A?A.brands.some(function(b){return(b=b.brand)&&b.indexOf(a)!=-1}):!1:!1}function B(a){return pa().indexOf(a)!=-1};function C(){return la?!!A&&A.brands.length>0:!1}function sa(){return C()?ra("Chromium"):(B("Chrome")||B("CriOS"))&&!(C()?0:B("Edge"))||B("Silk")};var ta=function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ua=function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},va=function(a,b){for(var c=a.length,d=Array(c),e=typeof a==="string"?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d},wa=function(a,b){var c=-1;ua(a,function(d,e){c=b.call(void 0,c,d,e,a)});
return c};function xa(a,b){b=ta(a,b);var c;(c=b>=0)&&Array.prototype.splice.call(a,b,1);return c}function ya(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function za(a){for(var b=[],c=0;c<a;c++)b[c]="";return b};var Aa=function(a){Aa[" "](a);return a};Aa[" "]=function(){};var Ba=function(a,b){try{return Aa(a[b]),!0}catch(c){}return!1};var Ca=B("Gecko")&&!(pa().toLowerCase().indexOf("webkit")!=-1&&!B("Edge"))&&!(B("Trident")||B("MSIE"))&&!B("Edge");!B("Android")||sa();sa();B("Safari")&&(sa()||(C()?0:B("Coast"))||(C()?0:B("Opera"))||(C()?0:B("Edge"))||(C()?ra("Microsoft Edge"):B("Edg/"))||C()&&ra("Opera"));var D=function(a,b){this.g=a===Da&&b||"";this.i=Ea};D.prototype.toString=function(){return this.g};var Ea={},Da={};function Fa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var Ga="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ha(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ga.length;f++)c=Ga[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var E,Ia=function(){if(E===void 0){var a=null,b=u.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:ka,createScript:ka,createScriptURL:ka})}catch(c){u.console&&u.console.error(c.message)}E=a}else E=a}return E};var Ja=function(a){this.g=a};Ja.prototype.toString=function(){return this.g+""};var Ka={},La=function(a){this.g=a};La.prototype.toString=function(){return this.g.toString()};var Ma=function(a){return a instanceof La&&a.constructor===La?a.g:"type_error:SafeHtml"},Na=function(a){var b=Ia();a=b?b.createHTML(a):a;return new La(a,Ka)};/*

 SPDX-License-Identifier: Apache-2.0
*/
var Pa=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'};var c=u.document.createElement("div");return a.replace(Oa,function(d,e){var f=b[d];if(f)return f;e.charAt(0)=="#"&&(e=Number("0"+e.slice(1)),isNaN(e)||(f=String.fromCharCode(e)));if(!f){f=Na(d+" ");if(c.nodeType===1&&(e=c.tagName,e==="SCRIPT"||e==="STYLE"))throw Error("");c.innerHTML=Ma(f);f=c.firstChild.nodeValue.slice(0,-1)}return b[d]=f})},Qa=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";
case "lt":return"<";case "gt":return">";case "quot":return'"';default:return c.charAt(0)!="#"||(c=Number("0"+c.slice(1)),isNaN(c))?b:String.fromCharCode(c)}})},Oa=/&([^;\s<&]+);?/g;var Sa=function(a,b){Fa(b,function(c,d){d=="style"?a.style.cssText=c:d=="class"?a.className=c:d=="for"?a.htmlFor=c:Ra.hasOwnProperty(d)?a.setAttribute(Ra[d],c):d.lastIndexOf("aria-",0)==0||d.lastIndexOf("data-",0)==0?a.setAttribute(d,c):a[d]=c})},Ra={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Ua=function(a,
b,c){var d=arguments,e=document,f=d[1];var h=String(d[0]);h=String(h);e.contentType==="application/xhtml+xml"&&(h=h.toLowerCase());h=e.createElement(h);f&&(typeof f==="string"?h.className=f:Array.isArray(f)?h.className=f.join(" "):Sa(h,f));d.length>2&&Ta(e,h,d);return h},Ta=function(a,b,c){function d(g){g&&b.appendChild(typeof g==="string"?a.createTextNode(g):g)}for(var e=2;e<c.length;e++){var f=c[e];if(!ha(f)||v(f)&&f.nodeType>0)d(f);else{a:{if(f&&typeof f.length=="number"){if(v(f)){var h=typeof f.item==
"function"||typeof f.item=="string";break a}if(typeof f==="function"){h=typeof f.item=="function";break a}}h=!1}ua(h?ya(f):f,d)}}},Va=function(a){return a.nodeType==9?a:a.ownerDocument||a.document};var Wa=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),Xa=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(d>=0){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var Ya=function(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)};function Za(a){var b,c;return(c=(b=/https?:\/\/[^\/]+/.exec(a))==null?void 0:b[0])!=null?c:""};var $a=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};u.addEventListener("test",c,b);u.removeEventListener("test",c,b)}catch(d){}return a}();function ab(a,b){if(typeof ReportingObserver==="undefined")return null;var c=function(e){e=r(e);for(var f=e.next();!f.done;f=e.next())f=f.value,a(f)&&b(f)},d=new ReportingObserver(c,{buffered:!0});u.addEventListener("pagehide",function(){c(d.takeRecords(),d);d.disconnect()});d.observe();return d};var bb={Da:"AdClickThru",Ea:"AdDurationChange",AD_ERROR:"AdError",Fa:"AdExpandedChange",Ga:"AdImpression",Ha:"AdInteraction",Ia:"AdLinearChange",Ja:"AdLoaded",Ka:"AdLog",La:"AdPaused",Ma:"AdPlaying",Na:"AdRemainingTimeChange",Oa:"AdSizeChange",Qa:"AdSkipped",Ra:"AdStarted",Sa:"AdStopped",Pa:"AdSkippableStateChange",Ta:"AdUserAcceptInvitation",Ua:"AdUserClose",Va:"AdUserMinimize",Wa:"AdVideoComplete",Xa:"AdVideoFirstQuartile",Ya:"AdVideoMidpoint",Za:"AdVideoStart",ab:"AdVideoThirdQuartile",bb:"AdVolumeChange",
cb:"Ping"};var cb=RegExp("^https?://(\\w|-)+\\.cdn\\.ampproject\\.(net|org)(\\?|/|$)"),gb=function(a){a=a||db();for(var b=new eb(u.location.href,!1),c=null,d=a.length-1,e=d;e>=0;--e){var f=a[e];!c&&cb.test(f.url)&&(c=f);if(f.url&&!f.Y){b=f;break}}e=null;f=a.length&&a[d].url;b.depth!=0&&f&&(e=a[d]);return new fb(b,e,c)},db=function(){var a=u,b=[],c=null;do{var d=a;try{var e=!!d&&d.location.href!=null&&Ba(d,"foo")}catch(h){e=!1}if(e){var f=d.location.href;c=d.document&&d.document.referrer||null}else f=c,c=null;
b.push(new eb(f||""));try{a=d.parent}catch(h){a=null}}while(a&&d!=a);d=0;for(a=b.length-1;d<=a;++d)b[d].depth=a-d;d=u;if(d.location&&d.location.ancestorOrigins&&d.location.ancestorOrigins.length==b.length-1)for(a=1;a<b.length;++a)f=b[a],f.url||(f.url=d.location.ancestorOrigins[a-1]||"",f.Y=!0);return b},fb=function(a,b,c){this.i=a;this.j=b;this.g=c},eb=function(a,b){this.url=a;this.Y=!!b;this.depth=null};var ib=function(a,b,c,d,e){var f=[];Ya(a,function(h,g){(h=hb(h,b,c,d,e))&&f.push(g+"="+h)});return f.join(b)},hb=function(a,b,c,d,e){if(a==null)return"";b=b||"&";c=c||",$";typeof c=="string"&&(c=c.split(""));if(a instanceof Array){if(d=d||0,d<c.length){for(var f=[],h=0;h<a.length;h++)f.push(hb(a[h],b,c,d+1,e));return f.join(c[d])}}else if(typeof a=="object")return e=e||0,e<2?encodeURIComponent(ib(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))};var jb=function(a,b){this.g=a;this.depth=b},lb=function(){var a=db(),b=Math.max(a.length-1,0),c=gb(a);a=c.i;var d=c.j,e=c.g,f=[];c=function(g,k){return g==null?k:g};e&&f.push(new jb([e.url,e.Y?2:0],c(e.depth,1)));d&&d!=e&&f.push(new jb([d.url,2],0));a.url&&a!=e&&f.push(new jb([a.url,0],c(a.depth,b)));var h=va(f,function(g,k){return f.slice(0,f.length-k)});!a.url||(e||d)&&a!=e||(d=Za(a.url))&&h.push([new jb([d,1],c(a.depth,b))]);h.push([]);return va(h,function(g){return kb(b,g)})};
function kb(a,b){var c=wa(b,function(e,f){return Math.max(e,f.depth)}),d=za(c+2);d[0]=a;ua(b,function(e){return d[e.depth+1]=e.g});return d}function mb(){var a=a===void 0?lb():a;return a.map(function(b){return hb(b)})};var nb=function(a){if(typeof DOMParser!="undefined"){var b=new DOMParser;a=Na(a===null?"null":a===void 0?"undefined":a);return b.parseFromString(Ma(a),"application/xml")}throw Error("Your browser does not support loading xml documents");};var F=function(){this.o=this.o;this.v=this.v};F.prototype.o=!1;F.prototype.dispose=function(){this.o||(this.o=!0,this.l())};F.prototype[Symbol.dispose]=function(){this.dispose()};F.prototype.l=function(){if(this.v)for(;this.v.length;)this.v.shift()()};var G=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.i=!1};G.prototype.stopPropagation=function(){this.i=!0};G.prototype.preventDefault=function(){this.defaultPrevented=!0};var H=function(a,b){G.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.g=null;a&&this.init(a,b)};x(H,G);var ob={2:"touch",3:"pen",4:"mouse"};
H.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;(b=a.relatedTarget)?Ca&&(Ba(b,"nodeName")||(b=null)):c=="mouseover"?b=a.fromElement:c=="mouseout"&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=d.clientX!==void 0?d.clientX:d.pageX,this.clientY=d.clientY!==void 0?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=a.clientX!==void 0?
a.clientX:a.pageX,this.clientY=a.clientY!==void 0?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=typeof a.pointerType==="string"?a.pointerType:ob[a.pointerType]||"";this.state=a.state;this.g=a;a.defaultPrevented&&H.T.preventDefault.call(this)};
H.prototype.stopPropagation=function(){H.T.stopPropagation.call(this);this.g.stopPropagation?this.g.stopPropagation():this.g.cancelBubble=!0};H.prototype.preventDefault=function(){H.T.preventDefault.call(this);var a=this.g;a.preventDefault?a.preventDefault():a.returnValue=!1};var I="closure_listenable_"+(Math.random()*1E6|0);var pb=0;var qb=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.L=e;this.key=++pb;this.R=this.W=!1},rb=function(a){a.R=!0;a.listener=null;a.proxy=null;a.src=null;a.L=null};var sb=function(a){this.src=a;this.g={};this.i=0};sb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.i++);var h=tb(a,b,d,e);h>-1?(b=a[h],c||(b.W=!1)):(b=new qb(b,this.src,f,!!d,e),b.W=c,a.push(b));return b};var ub=function(a,b){var c=b.type;c in a.g&&xa(a.g[c],b)&&(rb(b),a.g[c].length==0&&(delete a.g[c],a.i--))},tb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.R&&f.listener==b&&f.capture==!!c&&f.L==d)return e}return-1};var vb="closure_lm_"+(Math.random()*1E6|0),wb={},xb=0,zb=function(a,b,c,d,e){if(d&&d.once)yb(a,b,c,d,e);else if(Array.isArray(b))for(var f=0;f<b.length;f++)zb(a,b[f],c,d,e);else c=Ab(c),a&&a[I]?a.listen(b,c,v(d)?!!d.capture:!!d,e):Bb(a,b,c,!1,d,e)},Bb=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=v(e)?!!e.capture:!!e,g=Cb(a);g||(a[vb]=g=new sb(a));c=g.add(b,c,d,h,f);if(!c.proxy){d=Db();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)$a||(e=h),e===void 0&&(e=!1),a.addEventListener(b.toString(),
d,e);else if(a.attachEvent)a.attachEvent(Eb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");xb++}},Db=function(){var a=Fb,b=function(c){return a.call(b.src,b.listener,c)};return b},yb=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)yb(a,b[f],c,d,e);else c=Ab(c),a&&a[I]?a.g.add(String(b),c,!0,v(d)?!!d.capture:!!d,e):Bb(a,b,c,!0,d,e)},Gb=function(a,b,c,d,e){if(Array.isArray(b))for(var f=
0;f<b.length;f++)Gb(a,b[f],c,d,e);else(d=v(d)?!!d.capture:!!d,c=Ab(c),a&&a[I])?(a=a.g,b=String(b).toString(),b in a.g&&(f=a.g[b],c=tb(f,c,d,e),c>-1&&(rb(f[c]),Array.prototype.splice.call(f,c,1),f.length==0&&(delete a.g[b],a.i--)))):a&&(a=Cb(a))&&(b=a.g[b.toString()],a=-1,b&&(a=tb(b,c,d,e)),(c=a>-1?b[a]:null)&&Hb(c))},Hb=function(a){if(typeof a!=="number"&&a&&!a.R){var b=a.src;if(b&&b[I])ub(b.g,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?
b.detachEvent(Eb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);xb--;(c=Cb(b))?(ub(c,a),c.i==0&&(c.src=null,b[vb]=null)):rb(a)}}},Eb=function(a){return a in wb?wb[a]:wb[a]="on"+a},Fb=function(a,b){if(a.R)a=!0;else{b=new H(b,this);var c=a.listener,d=a.L||a.src;a.W&&Hb(a);a=c.call(d,b)}return a},Cb=function(a){a=a[vb];return a instanceof sb?a:null},Ib="__closure_events_fn_"+(Math.random()*1E9>>>0),Ab=function(a){if(typeof a==="function")return a;a[Ib]||(a[Ib]=function(b){return a.handleEvent(b)});
return a[Ib]};var K=function(){F.call(this);this.g=new sb(this);this.P=this;this.H=null};x(K,F);K.prototype[I]=!0;K.prototype.addEventListener=function(a,b,c,d){zb(this,a,b,c,d)};K.prototype.removeEventListener=function(a,b,c,d){Gb(this,a,b,c,d)};
var L=function(a,b){var c,d=a.H;if(d)for(c=[];d;d=d.H)c.push(d);a=a.P;d=b.type||b;if(typeof b==="string")b=new G(b,a);else if(b instanceof G)b.target=b.target||a;else{var e=b;b=new G(d,a);Ha(b,e)}e=!0;if(c)for(var f=c.length-1;!b.i&&f>=0;f--){var h=b.currentTarget=c[f];e=Jb(h,d,!0,b)&&e}b.i||(h=b.currentTarget=a,e=Jb(h,d,!0,b)&&e,b.i||(e=Jb(h,d,!1,b)&&e));if(c)for(f=0;!b.i&&f<c.length;f++)h=b.currentTarget=c[f],e=Jb(h,d,!1,b)&&e};
K.prototype.l=function(){K.T.l.call(this);if(this.g){var a=this.g,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,rb(d[e]);delete a.g[c];a.i--}}this.H=null};K.prototype.listen=function(a,b,c,d){return this.g.add(String(a),b,!1,c,d)};var Jb=function(a,b,c,d){b=a.g.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var h=b[f];if(h&&!h.R&&h.capture==c){var g=h.listener,k=h.L||h.src;h.W&&ub(a.g,h);e=g.call(k,d)!==!1&&e}}return e&&!d.defaultPrevented};var Kb=function(){};Kb.prototype.g=null;Kb.prototype.getOptions=function(){var a;(a=this.g)||(a=this.g={});return a};var Lb,Mb=function(){};x(Mb,Kb);Lb=new Mb;var M=function(a){K.call(this);this.headers=new Map;this.O=a||null;this.i=!1;this.A=this.m=null;this.G="";this.j=this.F=this.u=this.D=!1;this.J=null;this.M="";this.N=!1};x(M,K);var Nb=/^https?$/i,Ob=["POST","PUT"],Pb=[],Rb=function(a,b){var c=new M;Pb.push(c);b&&c.listen("complete",b);c.g.add("ready",c.U,!0,void 0,void 0);Qb(c,a)};M.prototype.U=function(){this.dispose();xa(Pb,this)};
var Qb=function(a,b){if(a.m)throw Error("[goog.net.XhrIo] Object is active with another request="+a.G+"; newUri="+b);a.G=b;a.D=!1;a.i=!0;a.m=new XMLHttpRequest;a.A=a.O?a.O.getOptions():Lb.getOptions();a.m.onreadystatechange=w(a.K,a);try{a.F=!0,a.m.open("GET",String(b),!0),a.F=!1}catch(e){Sb(a);return}b=new Map(a.headers);var c=Array.from(b.keys()).find(function(e){return"content-type"==e.toLowerCase()}),d=u.FormData&&!1;!(ta(Ob,"GET")>=0)||c||d||b.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
b=r(b);for(c=b.next();!c.done;c=b.next())d=r(c.value),c=d.next().value,d=d.next().value,a.m.setRequestHeader(c,d);a.M&&(a.m.responseType=a.M);"withCredentials"in a.m&&a.m.withCredentials!==a.N&&(a.m.withCredentials=a.N);try{Tb(a),a.u=!0,a.m.send(""),a.u=!1}catch(e){Sb(a)}},Sb=function(a){a.i=!1;a.m&&(a.j=!0,a.m.abort(),a.j=!1);Ub(a);Vb(a)},Ub=function(a){a.D||(a.D=!0,L(a,"complete"),L(a,"error"))};
M.prototype.abort=function(){this.m&&this.i&&(this.i=!1,this.j=!0,this.m.abort(),this.j=!1,L(this,"complete"),L(this,"abort"),Vb(this))};M.prototype.l=function(){this.m&&(this.i&&(this.i=!1,this.j=!0,this.m.abort(),this.j=!1),Vb(this,!0));M.T.l.call(this)};M.prototype.K=function(){this.o||(this.F||this.u||this.j?Wb(this):this.V())};M.prototype.V=function(){Wb(this)};
var Wb=function(a){if(a.i&&typeof fa!="undefined"&&(!a.A[1]||N(a)!=4||Xb(a)!=2))if(a.u&&N(a)==4){var b=a.K;if(typeof b==="function")a&&(b=w(b,a));else if(b&&typeof b.handleEvent=="function")b=w(b.handleEvent,b);else throw Error("Invalid listener argument");Number(0)>2147483647||u.setTimeout(b,0)}else if(L(a,"readystatechange"),N(a)==4){a.i=!1;try{Yb(a)?(L(a,"complete"),L(a,"success")):Ub(a)}finally{Vb(a)}}},Vb=function(a,b){if(a.m){Tb(a);var c=a.m,d=a.A[0]?function(){}:null;a.m=null;a.A=null;b||L(a,
"ready");try{c.onreadystatechange=d}catch(e){}}},Tb=function(a){a.J&&(u.clearTimeout(a.J),a.J=null)};M.prototype.isActive=function(){return!!this.m};
var Yb=function(a){var b=Xb(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=b===0)a=String(a.G).match(Wa)[1]||null,!a&&u.self&&u.self.location&&(a=u.self.location.protocol.slice(0,-1)),b=!Nb.test(a?a.toLowerCase():"");c=b}return c},N=function(a){return a.m?a.m.readyState:0},Xb=function(a){try{return N(a)>2?a.m.status:-1}catch(b){return-1}};var Zb=/^https?:\/\/ad.doubleclick.net\//,$b=/;dc_qid=([^;]+)/,ac=function(){this.statusText="";this.error=!1;this.g=0},cc=function(a,b,c){if(b=bc(b))a.i=c,a.g=1,Rb(b,function(d){a.g=0;d=d.target;if(Yb(d)){try{var e=d.m?d.m.responseText:""}catch(g){e=""}if((e=nb(e))&&e.documentElement&&e.getElementsByTagName("parsererror").length===0){if(typeof e.selectNodes!="undefined"){var f=Va(e);typeof f.setProperty!="undefined"&&f.setProperty("SelectionLanguage","XPath");e=e.selectNodes("/VAST/Ad")}else if(document.implementation.hasFeature("XPath",
"3.0")){f=Va(e);d=f.createNSResolver(f.documentElement);e=f.evaluate("/VAST/Ad",e,d,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);f=[];d=e.snapshotLength;for(var h=0;h<d;h++)f.push(e.snapshotItem(h));e=f}else e=[];e.length===0&&(a.g=2)}else a.statusText="XML error",a.error=!0}else{if(d==null)f=void 0;else try{f=N(d)>2?d.m.statusText:""}catch(g){f=""}a.statusText=(d==null?void 0:Xb(d))+" "+f;a.error=!0}a.i&&a.i()})},bc=function(a){try{if(!a)return null;var b=nb(a),c,d;if(typeof b.selectSingleNode!=
"undefined"){var e=Va(b);typeof e.setProperty!="undefined"&&e.setProperty("SelectionLanguage","XPath");var f=b.selectSingleNode("/VAST/Ad/*/Extensions/Extension[@type='DCMOriginalRequest']/RequestUrl")}else if(document.implementation.hasFeature("XPath","3.0")){e=Va(b);var h=e.createNSResolver(e.documentElement);f=e.evaluate("/VAST/Ad/*/Extensions/Extension[@type='DCMOriginalRequest']/RequestUrl",b,h,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue}else f=null;var g=(c=f)==null?void 0:(d=
c.firstChild)==null?void 0:d.nodeValue;if(!g||!Zb.test(g))return null;$b.exec(g);return g+";dc_rfl="+mb()[0]}catch(k){return null}};var O=function(a,b){this.j=this.v=this.l="";this.A=null;this.u=this.i="";this.o=!1;var c;a instanceof O?(this.o=b!==void 0?b:a.o,dc(this,a.l),this.v=a.v,this.j=a.j,ec(this,a.A),this.i=a.i,fc(this,gc(a.g)),this.u=a.u):a&&(c=String(a).match(Wa))?(this.o=!!b,dc(this,c[1]||"",!0),this.v=P(c[2]||""),this.j=P(c[3]||"",!0),ec(this,c[4]),this.i=P(c[5]||"",!0),fc(this,c[6]||"",!0),this.u=P(c[7]||"")):(this.o=!!b,this.g=new Q(null,this.o))};
O.prototype.toString=function(){var a=[],b=this.l;b&&a.push(R(b,hc,!0),":");var c=this.j;if(c||b=="file")a.push("//"),(b=this.v)&&a.push(R(b,hc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.A,c!=null&&a.push(":",String(c));if(c=this.i)this.j&&c.charAt(0)!="/"&&a.push("/"),a.push(R(c,c.charAt(0)=="/"?ic:jc,!0));(c=this.g.toString())&&a.push("?",c);(c=this.u)&&a.push("#",R(c,kc));return a.join("")};
O.prototype.resolve=function(a){var b=new O(this),c=!!a.l;c?dc(b,a.l):c=!!a.v;c?b.v=a.v:c=!!a.j;c?b.j=a.j:c=a.A!=null;var d=a.i;if(c)ec(b,a.A);else if(c=!!a.i){if(d.charAt(0)!="/")if(this.j&&!this.i)d="/"+d;else{var e=b.i.lastIndexOf("/");e!=-1&&(d=b.i.slice(0,e+1)+d)}e=d;if(e==".."||e==".")d="";else if(e.indexOf("./")!=-1||e.indexOf("/.")!=-1){d=e.lastIndexOf("/",0)==0;e=e.split("/");for(var f=[],h=0;h<e.length;){var g=e[h++];g=="."?d&&h==e.length&&f.push(""):g==".."?((f.length>1||f.length==1&&f[0]!=
"")&&f.pop(),d&&h==e.length&&f.push("")):(f.push(g),d=!0)}d=f.join("/")}else d=e}c?b.i=d:c=a.g.toString()!=="";c?fc(b,gc(a.g)):c=!!a.u;c&&(b.u=a.u);return b};
var dc=function(a,b,c){a.l=c?P(b,!0):b;a.l&&(a.l=a.l.replace(/:$/,""))},ec=function(a,b){if(b){b=Number(b);if(isNaN(b)||b<0)throw Error("Bad port number "+b);a.A=b}else a.A=null},fc=function(a,b,c){b instanceof Q?(a.g=b,lc(a.g,a.o)):(c||(b=R(b,mc)),a.g=new Q(b,a.o))},P=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},R=function(a,b,c){return typeof a==="string"?(a=encodeURI(a).replace(b,nc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},nc=function(a){a=
a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},hc=/[#\/\?@]/g,jc=/[#\?:]/g,ic=/[#\?]/g,mc=/[#\?@]/g,kc=/#/g,Q=function(a,b){this.i=this.g=null;this.j=a||null;this.l=!!b},S=function(a){a.g||(a.g=new Map,a.i=0,a.j&&Xa(a.j,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};Q.prototype.add=function(a,b){S(this);this.j=null;a=T(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.i+=1;return this};
var oc=function(a,b){S(a);b=T(a,b);a.g.has(b)&&(a.j=null,a.i-=a.g.get(b).length,a.g.delete(b))},pc=function(a,b){S(a);b=T(a,b);return a.g.has(b)};Q.prototype.forEach=function(a,b){S(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};var qc=function(a,b){S(a);var c=[];if(typeof b==="string")pc(a,b)&&(c=c.concat(a.g.get(T(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c};
Q.prototype.set=function(a,b){S(this);this.j=null;a=T(this,a);pc(this,a)&&(this.i-=this.g.get(a).length);this.g.set(a,[b]);this.i+=1;return this};Q.prototype.get=function(a,b){if(!a)return b;a=qc(this,a);return a.length>0?String(a[0]):b};
Q.prototype.toString=function(){if(this.j)return this.j;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=qc(this,d);for(var f=0;f<d.length;f++){var h=e;d[f]!==""&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}}return this.j=a.join("&")};
var gc=function(a){var b=new Q;b.j=a.j;a.g&&(b.g=new Map(a.g),b.i=a.i);return b},T=function(a,b){b=String(b);a.l&&(b=b.toLowerCase());return b},lc=function(a,b){b&&!a.l&&(S(a),a.j=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(oc(this,d),oc(this,e),c.length>0&&(this.j=null,this.g.set(T(this,e),ya(c)),this.i+=c.length))},a));a.l=b};var rc=/Android|iPhone|iPod/i,sc={wa:function(a){return ab(function(b){return b.body&&b.body.id==="HeavyAdIntervention"},a)}},U=function(){this.K="normal";this.O=!1;this.v=tc();this.H={};for(var a in bb)this.H[bb[a]]=[];this.j={};this.G=null;this.P=this.Z=this.U=!1;this.N=new ac},uc,vc,V=function(a,b,c,d){a.j[c]=d.bind(a);b.addEventListener?b.addEventListener(c,a.j[c],!1):b.attachEvent(c,a.j[c])},W=function(a,b,c){a.j[c]&&(b.removeEventListener?b.removeEventListener(c,a.j[c],!1):b.detachEvent&&b.detachEvent(c,
a.j[c]),delete a.j[c])},tc=function(){for(var a=u.document,b=RegExp("//imasdk.googleapis.com/js/sdkloader/vpaid_adapter[_a-z]*.js(\\?.*)?$"),c=null,d=0;d<a.scripts.length;d++)if(b.test(a.scripts[d].src)){c=a.scripts[d];break}if(c==null)return null;a=new O(c.src,!0);b=a.g.get("adTagUrl");if(!b||b.indexOf("http")!=0&&b.indexOf("//")!=0)return null;b=new O(b,!0);c=b.g.get("channel");d="vpaidadp_html5";c&&(d=c+"+"+d);b.g.set("channel",d);(c=a.g.get("correlator"))&&(wc=+c||-1);(c=a.g.get("scor"))&&(xc=
+c||-1);c=a.g.get("vpa");if(c=="1"||c=="0")uc=c=="1";c=a.g.get("vpmute");if(c=="1"||c=="0")vc=c=="1";yc(a,b);return b},yc=function(a,b){b.l=="https"&&["rdid","is_lat","idtype"].forEach(function(c){var d=a.g.get(c);d&&b.g.set(c,d)})},Ac=function(a,b,c){b=b===void 0?"Error":b;if(c){var d=c.toString();c.name&&d.indexOf(c.name)==-1&&(d+=": "+c.name);c.message&&d.indexOf(c.message)==-1&&(d+=": "+c.message);if(c.stack)a:{c=c.stack;var e=d;try{c.indexOf(e)==-1&&(c=e+"\n"+c);for(var f;c!=f;)f=c,c=c.replace(RegExp("((https?:/..*/)[^/:]*:\\d+(?:.|\n)*)\\2"),
"$1");d=c.replace(RegExp("\n *","g"),"\n");break a}catch(h){d=e;break a}d=void 0}b+=": "+d}a.P=!0;X(a,b);zc(a)},Bc=function(a){if(a.Z&&a.N.g===0&&a.M&&a.J&&(a.v||a.D)){a.A=Ua("DIV",{style:"position: absolute; z-index: 99; width: 100%; height: 100%"});a.M.insertBefore(a.A,a.M.firstChild);a.F=new google.ima.AdDisplayContainer(a.A,a.J);a.F.initialize();a.o=new google.ima.AdsLoader(a.F);var b=new google.ima.AdsRequest,c=uc;c!=null&&b.setAdWillAutoPlay(c);c=vc;c!=null&&b.setAdWillPlayMuted(c);a.v?(b.adTagUrl=
a.v.toString(),b.linearAdSlotHeight=a.l,b.linearAdSlotWidth=a.u,b.nonLinearAdSlotHeight=a.l,b.nonLinearAdSlotWidth=a.u):b.adsResponse=a.D;V(a,a.o,google.ima.AdsManagerLoadedEvent.Type.ADS_MANAGER_LOADED,a.ra);V(a,a.o,google.ima.AdErrorEvent.Type.AD_ERROR,a.aa);a.o.requestAds(b)}};m=U.prototype;m.na=function(){this.N.g===2?(this.P=!0,this.i("AdError")):Bc(this)};m.oa=function(){return"2.0"};
m.pa=function(a,b,c,d,e,f){this.u=a;this.l=b;this.K=c=="fullscreen"?c:"normal";a=f&&f.slot;f=f&&f.videoSlot;if(e=(e=e&&e.AdParameters)?e.indexOf("&")!=-1?"document"in u?Pa(e):Qa(e):e:null)this.D=e;Cc(this);a&&f&&(this.v||this.D)?(cc(this.N,this.D,this.na.bind(this)),this.M=a,this.J=f,rc.test(u.navigator.userAgent)&&this.J.load(),Bc(this)):Ac(this,"Error during init:"+(a?"":" ad slot is missing")+(f?"":" video slot is missing")+(this.v||this.D?"":" no ad VAST or URL found"))};
m.Ba=function(){if(Y(this))try{this.g.init(this.u,this.l,this.K),this.g.start()}catch(a){Ac(this,"",a)}else X(this)};m.Ca=function(){this.U?Dc(this):Y(this)?this.g.stop():X(this)};m.va=function(){Y(this)?this.g.pause():X(this)};m.ya=function(){Y(this)?this.g.resume():X(this)};m.xa=function(a,b,c){Y(this)?(this.u=a,this.l=b,this.K=c=="fullscreen"?c:"normal",this.g.resize(this.u,this.l,this.K),this.i("AdSizeChange")):X(this)};
m.da=function(){Y(this)?(this.g.expand(),this.O=!0,this.i("AdExpandedChange")):X(this)};m.ca=function(){Y(this)?(this.g.collapse(),this.O=!1,this.i("AdExpandedChange")):X(this)};m.Aa=function(){Y(this)?this.g.getAdSkippableState()&&this.g.skip():X(this)};m.subscribe=function(a,b,c){if(b=this.H[b]){var d={};d.L=a;d.scope=c;b.push(d)}};m.ba=function(a,b){var c=this.H[b],d=[];c&&(c.forEach(function(e){e.L!=a&&d.push(e)}),this.H[b]=d)};m.ja=function(){return!0};m.ma=function(){return this.u};m.ha=function(){return this.l};
m.ga=function(){return this.O};m.getAdSkippableState=function(){return this.g?this.g.getAdSkippableState():!1};m.ka=function(){var a=-2;this.g&&(a=this.g.getRemainingTime(),a==-1&&(a=-2));return a};m.fa=function(){return this.V?this.V.getDuration():-2};m.la=function(){return this.g?this.g.getVolume():-1};m.za=function(a){this.g&&this.g.setVolume(a)};m.ea=function(){return""};m.ia=function(){return!1};
var Y=function(a){return!a.P&&a.g!=null},zc=function(a){a.g&&(a.g.destroy(),W(a,a.g,google.ima.AdEvent.Type.IMPRESSION),W(a,a.g,google.ima.AdEvent.Type.STARTED),W(a,a.g,google.ima.AdEvent.Type.CLICK),W(a,a.g,google.ima.AdEvent.Type.FIRST_QUARTILE),W(a,a.g,google.ima.AdEvent.Type.MIDPOINT),W(a,a.g,google.ima.AdEvent.Type.THIRD_QUARTILE),W(a,a.g,google.ima.AdEvent.Type.COMPLETE),W(a,a.g,google.ima.AdEvent.Type.PAUSED),W(a,a.g,google.ima.AdEvent.Type.RESUMED),W(a,a.g,google.ima.AdEvent.Type.SKIPPED),
W(a,a.g,google.ima.AdEvent.Type.SKIPPABLE_STATE_CHANGED),W(a,a.g,google.ima.AdEvent.Type.VOLUME_CHANGED),W(a,a.g,google.ima.AdEvent.Type.VOLUME_MUTED),W(a,a.g,google.ima.AdEvent.Type.USER_CLOSE),W(a,a.g,google.ima.AdEvent.Type.LOADED),W(a,a.g,google.ima.AdEvent.Type.LOG),W(a,a.g,google.ima.AdEvent.Type.ALL_ADS_COMPLETED),W(a,a.g,google.ima.AdErrorEvent.Type.AD_ERROR),delete a.g);a.o&&(a.o.destroy(),delete a.o);a.F&&(a.F.destroy(),delete a.F);if(a.A){var b=a.A;b&&b.parentNode&&b.parentNode.removeChild(b);
delete a.A}};U.prototype.i=function(a,b){(a=this.H[a])&&a.forEach(function(c){c.L.apply(c.scope,b)})};var X=function(a,b){a.i("AdError",b?[b]:void 0)},Ec=function(a){a.G==null&&(a.G=u.setInterval(U.prototype.i.bind(a,"AdRemainingTimeChange"),500))},Fc=function(a){a.G!=null&&(u.clearInterval(a.G),a.G=null)};m=U.prototype;
m.ta=function(a){this.Z=!0;a.target!=null&&(W(this,a.target,"load"),W(this,a.target,"error"));google.ima.settings.setVpaidMode(google.ima.ImaSdkSettings.VpaidMode.INSECURE);google.ima.settings.setIsVpaidAdapter(!0);wc>0&&google.ima.settings.setPageCorrelator(wc);xc>0&&google.ima.settings.setStreamCorrelator(xc);Bc(this)};m.ua=function(a){a.target&&(W(this,a.target,"load"),W(this,a.target,"error"));Ac(this,"SdkLoadError")};
m.ra=function(a){this.g=a.getAdsManager(this.J);V(this,this.g,google.ima.AdEvent.Type.IMPRESSION,this.C);V(this,this.g,google.ima.AdEvent.Type.STARTED,this.C);V(this,this.g,google.ima.AdEvent.Type.CLICK,this.C);V(this,this.g,google.ima.AdEvent.Type.FIRST_QUARTILE,this.C);V(this,this.g,google.ima.AdEvent.Type.MIDPOINT,this.C);V(this,this.g,google.ima.AdEvent.Type.THIRD_QUARTILE,this.C);V(this,this.g,google.ima.AdEvent.Type.COMPLETE,this.C);V(this,this.g,google.ima.AdEvent.Type.PAUSED,this.C);V(this,
this.g,google.ima.AdEvent.Type.RESUMED,this.C);V(this,this.g,google.ima.AdEvent.Type.SKIPPED,this.C);V(this,this.g,google.ima.AdEvent.Type.SKIPPABLE_STATE_CHANGED,this.C);V(this,this.g,google.ima.AdEvent.Type.VOLUME_CHANGED,this.C);V(this,this.g,google.ima.AdEvent.Type.VOLUME_MUTED,this.C);V(this,this.g,google.ima.AdEvent.Type.USER_CLOSE,this.C);V(this,this.g,google.ima.AdEvent.Type.LOADED,this.qa);V(this,this.g,google.ima.AdEvent.Type.ALL_ADS_COMPLETED,this.sa);V(this,this.g,google.ima.AdErrorEvent.Type.AD_ERROR,
this.aa);this.i("AdLoaded")};
m.C=function(a){switch(a.type){case google.ima.AdEvent.Type.IMPRESSION:this.i("AdImpression");break;case google.ima.AdEvent.Type.STARTED:this.i("AdStarted");this.i("AdVideoStart");Ec(this);break;case google.ima.AdEvent.Type.CLICK:this.i("AdClickThru",["","",!1]);break;case google.ima.AdEvent.Type.FIRST_QUARTILE:this.i("AdVideoFirstQuartile");break;case google.ima.AdEvent.Type.MIDPOINT:this.i("AdVideoMidpoint");break;case google.ima.AdEvent.Type.THIRD_QUARTILE:this.i("AdVideoThirdQuartile");break;
case google.ima.AdEvent.Type.COMPLETE:this.i("AdVideoComplete");break;case google.ima.AdEvent.Type.PAUSED:this.i("AdPaused");Fc(this);break;case google.ima.AdEvent.Type.RESUMED:this.i("AdPlaying");Ec(this);break;case google.ima.AdEvent.Type.SKIPPED:this.i("AdSkipped");Fc(this);break;case google.ima.AdEvent.Type.SKIPPABLE_STATE_CHANGED:this.i("AdSkippableStateChange");break;case google.ima.AdEvent.Type.VOLUME_CHANGED:case google.ima.AdEvent.Type.VOLUME_MUTED:this.i("AdVolumeChange");break;case google.ima.AdEvent.Type.USER_CLOSE:this.i("AdUserClose")}};
m.qa=function(a){this.V=a.getAd()};m.aa=function(a){a=a.getError?a.getError():null;var b="AdError"+(a?" "+a.getErrorCode()+" ("+a.getMessage()+")":"");Ac(this,b,a)};m.sa=function(){this.U=!0;Fc(this);Dc(this)};var Dc=function(a){u.setTimeout(function(){zc(a);a.i("AdStopped")},100)},Cc=function(a){sc.wa(function(b){a.i("AdError",["HeavyAdIntervention: "+b.body.message])})},Gc=function(){var a="X";U.X&&U.hasOwnProperty(a)?a=U.X:(a=new U,U.X=a);return a},wc=-1,xc=-1;var Hc=Gc(),Ic=new D(Da,"//imasdk.googleapis.com/js/sdkloader/ima3.js"),Z=Ua("SCRIPT");Z.type="text/javascript";var Jc,Kc=Ic instanceof D&&Ic.constructor===D&&Ic.i===Ea?Ic.g:"type_error:Const",Lc=Ia(),Mc=Lc?Lc.createScriptURL(Kc):Kc;Jc=new Ja(Mc,{});Z.src=Jc instanceof Ja&&Jc.constructor===Ja?Jc.g:"type_error:TrustedResourceUrl";var Nc,Oc,Pc,Qc=(Pc=(Oc=(Z.ownerDocument&&Z.ownerDocument.defaultView||window).document).querySelector)==null?void 0:Pc.call(Oc,"script[nonce]");
(Nc=Qc?Qc.nonce||Qc.getAttribute("nonce")||"":"")&&Z.setAttribute("nonce",Nc);V(Hc,Z,"load",Hc.ta);V(Hc,Z,"error",Hc.ua);var Rc=u.document;(Rc.body||Rc.head).appendChild(Z);U.prototype.handshakeVersion=U.prototype.oa;U.prototype.initAd=U.prototype.pa;U.prototype.resizeAd=U.prototype.xa;U.prototype.startAd=U.prototype.Ba;U.prototype.stopAd=U.prototype.Ca;U.prototype.pauseAd=U.prototype.va;U.prototype.resumeAd=U.prototype.ya;U.prototype.expandAd=U.prototype.da;U.prototype.collapseAd=U.prototype.ca;
U.prototype.skipAd=U.prototype.Aa;U.prototype.subscribe=U.prototype.subscribe;U.prototype.unsubscribe=U.prototype.ba;U.prototype.getAdLinear=U.prototype.ja;U.prototype.getAdWidth=U.prototype.ma;U.prototype.getAdHeight=U.prototype.ha;U.prototype.getAdExpanded=U.prototype.ga;U.prototype.getAdSkippableState=U.prototype.getAdSkippableState;U.prototype.getAdRemainingTime=U.prototype.ka;U.prototype.getAdDuration=U.prototype.fa;U.prototype.getAdVolume=U.prototype.la;U.prototype.setAdVolume=U.prototype.za;
U.prototype.getAdCompanions=U.prototype.ea;U.prototype.getAdIcons=U.prototype.ia;u.getVPAIDAd=function(){return Gc()};}).call(this);
